### ISSUE TITLE
Peer connection failure: werift server and sipsorcery client

### ISSUE THREAD

**Issue by sipsorcery** [sipsorcery/webrtc-echoes#11]
I'm logging this as a way to keep track of the tests I've run and where I'm yet to identify the cause of the failure.

Client and server applications are both being run on the same machine.

Operating System: Win 10 Pro x64 10.0.19042
node.js version: v14.15.5
dotnet version: 5.0.103

**server console log**
````
C:\Dev\sipsorcery\webrtc-echoes\werift>npm run server

> werift-echo@1.0.0 server C:\Dev\sipsorcery\webrtc-echoes\werift
> ts-node-dev server

[INFO] 19:33:53 ts-node-dev ver. 1.1.1 (using ts-node ver. 9.1.1, typescript ver. 4.1.5)
(node:25984) UnhandledPromiseRejectionWarning: Error:
    at C:\Dev\sipsorcery\webrtc-echoes\werift\node_modules\werift\lib\index.js:11281:23
    at Array.forEach (<anonymous>)
    at Function.parse (C:\Dev\sipsorcery\webrtc-echoes\werift\node_modules\werift\lib\index.js:11277:21)
    at RTCPeerConnection.setLocalDescription (C:\Dev\sipsorcery\webrtc-echoes\werift\node_modules\werift\lib\index.js:11936:48)
    at C:\Dev\sipsorcery\webrtc-echoes\werift\server.ts:52:27
    at Generator.next (<anonymous>)
    at fulfilled (C:\Dev\sipsorcery\webrtc-echoes\werift\node_modules\tslib\tslib.js:114:62)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:25984) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:25984) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
````

**client console log**
````
C:\Dev\sipsorcery\webrtc-echoes\sipsorcery\client>dotnet run
Starting webrtc echo test client.
[19:34:00 DBG] CreateRtpSocket attempting to create and bind RTP socket(s) on [::]:0.
[19:34:00 DBG] CreateBoundUdpSocket attempting to create and bind UDP socket(s) on [::]:0.
[19:34:00 DBG] CreateBoundUdpSocket successfully bound on [::]:62870, dual mode True.
[19:34:00 DBG] Successfully bound RTP socket [::]:62870 (dual mode True).
[19:34:00 DBG] RTPChannel for [::]:62870 started.
[19:34:00 DBG] RTP ICE Channel discovered 3 local candidates.
[19:34:00 INF] Signaling state changed to have_local_offer.
[19:34:02 DBG] Adding peer reflex ICE candidate for 192.168.11.50:57270.
[19:34:02 DBG] Adding new candidate pair to checklist for: udp:[::]:62870 (host)->udp:192.168.11.50:57270 (prflx)
[19:34:02 DBG] Adding peer reflex ICE candidate for 192.168.0.50:57270.
[19:34:02 DBG] Adding new candidate pair to checklist for: udp:[::]:62870 (host)->udp:192.168.0.50:57270 (prflx)
[19:34:02 DBG] Adding peer reflex ICE candidate for [2a02:8084:6981:7880::3]:57271.
[19:34:02 DBG] Adding new candidate pair to checklist for: udp:[::]:62870 (host)->udp:[2a02:8084:6981:7880::3]:57271 (prflx)
Unhandled exception. System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
````

**Comment by shinyoshiaki** [comment]
Seems cause by using not supported codecs.
 I fixed codec problem at `webrtc-echoes` master branch. 
Please npm install again, werift will update to latest version.

**Comment by shinyoshiaki** [comment]
![Screenshot from 2021-02-15 20-19-08](https://user-images.githubusercontent.com/16427740/107940137-1b2e5e80-6fcb-11eb-9e77-20c8df53dd50.png)

Failed at DTLS cipher suite negotiation.
werift only supporting X25519 now.

**Comment by sipsorcery** [comment]
So the problem here is the werift DTLS module does not yet support ECDSA curve `secp256r1`? 

In the screenshots below, of a Bouncy Castle DTLS Client Hello and the werift DTLS Client Hello, they do have a common `secp256r1` group, but of course that could still mean the curve is not supported further up the stack. I will have a look at the Bouncy Castle documentation and see if there's a way to support the `x25519` curve.

Bouncy Castle DTLS Hello:

![bc_dtls_client_hello](https://user-images.githubusercontent.com/197660/107956810-9d9d2b00-6f97-11eb-95f7-e6ca6b00cbde.png)

werift DTLS Client Hello:

![werift_dtls_client_hello](https://user-images.githubusercontent.com/197660/107956871-b60d4580-6f97-11eb-9983-bf19a923b125.png)

**Comment by sipsorcery** [comment]
And just for completeness after applying the werift update the console output is now as below, which corresponds to the point above about the `secp256r1`, curve not yet being supported.

````
[INFO] 13:57:07 ts-node-dev ver. 1.1.1 (using ts-node ver. 9.1.1, typescript ver. 4.1.5)
Error: todo support namedCurveP256
    at prfPreMasterSecret (C:\Dev\sipsorcery\webrtc-echoes\werift\node_modules\werift\lib\index.js:5544:19)
    at C:\Dev\sipsorcery\webrtc-echoes\werift\node_modules\werift\lib\index.js:7231:29
    at C:\Dev\sipsorcery\webrtc-echoes\werift\node_modules\werift\lib\index.js:7126:15
    at Array.forEach (<anonymous>)
    at Flight5.exec (C:\Dev\sipsorcery\webrtc-echoes\werift\node_modules\werift\lib\index.js:7121:18)
    at DtlsClient.handleHandshakes (C:\Dev\sipsorcery\webrtc-echoes\werift\node_modules\werift\lib\index.js:7309:78)
    at IceTransport.DtlsClient.udpOnMessage [as onData] (C:\Dev\sipsorcery\webrtc-echoes\werift\node_modules\werift\lib\index.js:7256:30)
    at Object.execute (C:\Dev\sipsorcery\webrtc-echoes\werift\node_modules\werift\lib\index.js:7491:26)
    at Event.execute (C:\Dev\sipsorcery\webrtc-echoes\werift\node_modules\rx.mini\src\core\index.ts:20:19)
    at Connection.dataReceived (C:\Dev\sipsorcery\webrtc-echoes\werift\node_modules\werift\lib\index.js:9114:21)
[ERROR] 13:57:18 Error: todo support namedCurveP256
````

**Comment by shinyoshiaki** [comment]
The Client Hello generated by werift contains a dummy secp256. (I remember adding it to bypass validation when connecting to OpenSSL.)
Actually I did not implementation about secp256r1. so I need to implement it.

**Comment by sipsorcery** [comment]
Unfortunately `curve25519` support hasn't made it into the [C# Bouncy Castle library](https://github.com/bcgit/bc-csharp/blob/860ce04ebcf75718e94cdadcd486895d67fd7e98/crypto/src/crypto/tls/NamedCurve.cs#L17) yet. It is in the [Java version](https://github.com/bcgit/bc-java/blob/bc3b92f1f0e78b82e2584c5fb4b226a13e7f8b3b/tls/src/main/java/org/bouncycastle/tls/NamedGroup.java#L53) so hopefully it will get ported across at some point.

For tracking https://github.com/bcgit/bc-csharp/issues/288.

**Comment by shinyoshiaki** [comment]
I implemented secp256r1 and extended master secret.

Now werift server and sipsorcery client dtls connection seems working well.

But werift client and sipsorcery server does'nt working still now.

**werift server x sipsorcery client**
![Screenshot from 2021-02-21 16-01-01](https://user-images.githubusercontent.com/16427740/108618100-a5a90f00-745e-11eb-93e5-0b6f96033337.png)

**werift client x sipsorcery server**
![Screenshot from 2021-02-21 16-06-25](https://user-images.githubusercontent.com/16427740/108618116-c4a7a100-745e-11eb-97c7-02af77c1d37a.png)

**Comment by sipsorcery** [comment]
The failure is the same one that sipsorcery had with [Pion's DTLS stack](https://github.com/pion/dtls/issues/274). The Bouncy Castle DTLS implementation requires the [renegotiation extension](https://github.com/bcgit/bc-csharp/blob/cc7fbb6bbe56f107cd4c54bcc1691911a851cd1a/crypto/src/crypto/tls/AbstractTlsPeer.cs#L55) to be set.

There are other WebRTC stacks, such as Jitsi, using Bouncy Castle's DTLS so it may be worth fixing. The [Pion fix](https://github.com/pion/dtls/pull/314) doesn't look to big.

**Comment by shinyoshiaki** [comment]
I implemented renegotiation indication extension.
Now werift client x sipsorcery server seems working well

**Comment by sipsorcery** [comment]
Works for me as well!

**Comment by Sean-Der** [comment]
Amazing work @shinyoshiaki i am impressed/happy how quick this is all coming together.

@sipsorcery it is so great you started this. It is gonna have such a big impact. I can’t wait to announce and for people to see what is possible with WebRTC today! Go/C#/Typescript covers so many programmers that are frustrated today :)
