### ISSUE TITLE
Peer connection failure: sipsorcery server and pion client

### ISSUE THREAD

**Issue by sipsorcery** [sipsorcery/webrtc-echoes#14]
The DTLS handshake is failing due to the Bouncy Castle DTLS stack used by sipsorcery requiring the renegotiation extension.

Have added a note in the [pion DTLS PR](https://github.com/pion/dtls/pull/314).

**Comment by Sean-Der** [comment]
Hey @sipsorcery when Pion acts a client we insert the extension [here](https://github.com/pion/dtls/blob/master/flight1handler.go#L61-L63)

As a server it is [here](https://github.com/pion/dtls/blob/master/flight3handler.go#L143-L145)

This first showed up in `v2.0.4`. Can you share a pcap, having a hard time reproducing :(

**Comment by sipsorcery** [comment]
I've added the packet captures to the [DTLS Pull Request](https://github.com/pion/dtls/pull/314#issuecomment-779121176).

It's also worth noting that the peer connection does succeed for pion server and sipsorcery client.

To reproduce:

 - Run the sipsorcery echo server using: `webrtc-echoes\sipsorcery\server>dotnet run`
 - Run the pion echo test client (which I'll merge in now): `webrtc-echoes\pion\client>go build main.go && main.exe`

The sipsorcery console log:

````
C:\Dev\sipsorcery\webrtc-echoes\sipsorcery\server>dotnet run
10:26:36.180 INF >> [WebServer] Running HTTPListener: Unosquare HTTP Listener
 10:26:36.199 INF >> [WebServer] Web server prefix 'http://*:8080/' added.
WebServer New State - Loading
WebServer New State - Listening
ctrl-c to exit.
 10:26:36.270 INF >> [WebServer] Started HTTP Listener
[10:26:42 INF] ICE connection state changed to checking.
[10:26:42 INF] Signaling state changed to have_remote_offer.
[10:26:42 WRN] Media announcement for audio omitted due to no reciprocal remote announcement.
[10:26:42 INF] Signaling state changed to have_local_offer.
[10:26:42 WRN] Media announcement for audio omitted due to no reciprocal remote announcement.
 10:26:42.704 INF >> [WebServer] [tiXgwbgkkU+WOlI53EBM9g] POST /offer: "200 OK" sent in 1974ms (0 bytes)
[10:26:42 INF] ICE RTP channel connected after 439ms udp:[::]:52361 (host)->udp:192.168.11.50:52352 (prflx).
[10:26:42 INF] ICE connection state changed to connected.
[10:26:42 INF] Peer connection state changed to connecting.
[10:26:42 INF] ICE connected to remote end point 192.168.11.50:52352.
[10:26:42 WRN] DTLS client raised unexpected alert: fatal(2), handshake_failure(40), .
[10:26:42 WRN] DTLS handshake as client failed. handshake_failure(40)
Org.BouncyCastle.Crypto.Tls.TlsFatalAlert: handshake_failure(40)
   at Org.BouncyCastle.Crypto.Tls.DtlsClientProtocol.Connect(TlsClient client, DatagramTransport transport) in /_/crypto/src/crypto/tls/DtlsClientProtocol.cs:line 58
   at SIPSorcery.Net.DtlsSrtpTransport.DoHandshakeAsClient()
[10:26:42 WRN] RTCPeerConnection DTLS handshake failed.
[10:26:42 INF] Peer connection state changed to failed.
[10:26:42 INF] Peer connection state changed to closed.
````

The pion console log:
````
C:\Dev\sipsorcery\webrtc-echoes\pion\client>go build main.go && main.exe
Offer:
v=0
o=- 4197039829075547640 1613384800 IN IP4 0.0.0.0
s=-
t=0 0
a=fingerprint:sha-256 92:D6:55:C4:4E:A7:87:4D:4F:A5:ED:A6:2E:E4:75:3E:BF:B7:58:AA:77:0D:03:52:35:C2:A7:8C:70:8A:64:2E
a=group:BUNDLE 0
m=video 9 UDP/TLS/RTP/SAVPF 96
c=IN IP4 0.0.0.0
a=setup:actpass
a=mid:0
a=ice-ufrag:qznCcHjzkvoPvgdw
a=ice-pwd:qlWWDiAUtvthLBrVNKZCjBBIdbXuvosr
a=rtcp-mux
a=rtcp-rsize
a=rtpmap:96 VP8/90000
a=ssrc:4116741611 cname:pion
a=ssrc:4116741611 msid:pion video
a=ssrc:4116741611 mslabel:pion
a=ssrc:4116741611 label:video
a=msid:pion video
a=sendrecv

Attempting to POST offer to http://localhost:8080/offer.
response Status: 200 OK
response Headers: map[Access-Control-Allow-Origin:[*] Connection:[close] Content-Encoding:[identity] Content-Type:[application/json; charset=utf-8] Date:[Mon, 15 Feb 2021 10:26:42 GMT] Server:[EmbedIO/3.4.3] Vary:[Accept-Encoding]]
response Body: {"type":"answer","sdp":"v=0\r\no=- 50158 0 IN IP4 127.0.0.1\r\ns=sipsorcery\r\nt=0 0\r\na=fingerprint:sha-256 12:A8:50:9B:6C:FC:29:B0:46:34:82:DF:2B:C1:16:5A:4A:AC:30:03:61:CF:08:6B:45:3C:28:48:FC:0C:B3:46\r\na=group:BUNDLE 0\r\nm=video 9 UDP/TLS/RTP/SAVP 96\r\nc=IN IP4 0.0.0.0\r\na=ice-ufrag:MEGA\r\na=ice-pwd:BBBKMBLLQWQWBSJIYSFDFRXW\r\na=fingerprint:sha-256 12:A8:50:9B:6C:FC:29:B0:46:34:82:DF:2B:C1:16:5A:4A:AC:30:03:61:CF:08:6B:45:3C:28:48:FC:0C:B3:46\r\na=candidate:2944 1 udp 659136 192.168.11.50 52361 typ host generation 0\r\na=candidate:2488 1 udp 659136 192.168.0.50 52361 typ host generation 0\r\na=candidate:2547 1 udp 659136 2a02:8084:6981:7880::3 52361 typ host generation 0\r\na=ice-options:ice2,trickle\r\na=mid:0\r\na=rtpmap:96 VP8/90000\r\na=rtcp-mux\r\na=rtcp:9 IN IP4 0.0.0.0\r\na=end-of-candidates\r\na=setup:active\r\na=sendrecv\r\na=ssrc:991311375 cname:efe4afe1-2d34-447a-97d6-943d7723e883\r\n"}
Signaling state has changed to stable.
ICE connection state has changed checking.
ICE connection state has changed connected.
Peer connection state has changed to failed.
ICE connection state has changed disconnected.
ICE connection state has changed failed.
````

**Comment by Sean-Der** [comment]
Hey @sipsorcery can you try `v3.0.10` 

That has the new version of `pion/dtls` that includes `RenegotationInfo` in the `ServerHello` when appropriate! This weekend I will get myself some C# knowledge, never used it before myself :)

**Comment by sipsorcery** [comment]
@Sean-Der thx for the fix.

Still failing though. I didn't dig into it yet but did I spot somewhere that the `renegotiation_info` extension only gets set by the pion DTLS server logic if the DTLS client initially sets it? The Bouncy Castle DTLS client doesn't.

Even though the BC DTLS client doesn't set it it does seem to require it in the `Server Hello`. I can do some more digging tomorrow to track down the underlying DTLS mechanism.

**Comment by Sean-Der** [comment]
Crud I misunderstood! Ok let me make it always on and will give you another release. Sorry about the churn

**Comment by Sean-Der** [comment]
Ok mind trying again? Just do `go get -u github.com/pion/webrtc/v3@serverhello-always-include-renegotation-info && go mod tidy` and should use everything properly.

If that works will tag new version :)

**Comment by sipsorcery** [comment]
Bingo. The DTLS negotiation and peer connection set up now succeed with my WebRTC server.

**Comment by Sean-Der** [comment]
:fire: tagged `v3.0.10` will follow up on the other Pion failure now :)
